Migrate codebase to python3
NordicSemiconductor/piccata pull request #6
Opened 2019-08-23 09:15 UTC by shalak

2019-09-30 15:28 UTC, alwa-nordic requested changes
As a small aside that may be not relevant to this pull request: The `is` operator is used a lot in this code base. In all cases I've seen, it's incorrect, and should have been `==` instead. In some places, it works only because of internal details of CPython and the particular values compared.

2019-09-30 15:28 UTC, alwa-nordic commented on piccata/resource.py
> +            response = message.Message.AckMessage(request, code=METHOD_NOT_ALLOWED, payload=b"Error: Method not recognized!")
This looks suspicious to me: METHOD_NOT_ALLOWED. The appropriate response to unknown methods is "Not Implemented" in HTTP and thus in CoAP, which borrows the semantics. This code is not covered by tests. We don't need to fix this in this merge.

2019-09-30 15:28 UTC, alwa-nordic commented on piccata/core.py
>  class _CoapMessageLayer(object):
Method `_remove_outdated_messages` is not Python 3, where `sys.intmax` does not exist.

2019-09-30 15:28 UTC, alwa-nordic commented on piccata/option.py
>          for segment in segments:
Line below (but posting here due to GitHub limitation): We probably don't want `str` there. The tests make segment a `bytes`, which will get mangled by `str`.

2019-09-30 15:28 UTC, alwa-nordic commented on piccata/option.py
> +        if isinstance(segments, str):
Why `str` in particular? I'm guessing it is because a `str` here will give the particularly pathological behavior of interpreting each character in the `str` as a segment. But a `bytes` will also cause bad behavior here because we don't check the type of each segment. This pattern of blacklisting a type is used in several places in the code. Maybe it's less work to just constrain the type to a list until someone complains?

2019-09-30 15:28 UTC, alwa-nordic commented on piccata/option.py
Above: Test `test_coap_core.py` causes `self.uri_path` to be a `Tuple[bytes]`, while `test_message_options.py` causes it to be `List[str]`. In the first case `'/'` should be `b'/'` here and it blows up. Please determine the most appropriate type for self.uri_path, and update the program. I think we should start adding type annotations to document the usage of this API. If possible, please add test coverage for this method.

2019-09-30 15:28 UTC, alwa-nordic commented on tests/test_message_option.py
> +        binary1 = bytes([(64)]+[(0)]+[(0)]+[(0)])
This can be written more clearly as `bytes([64, 0, 0, 0])`

2019-09-30 15:28 UTC, alwa-nordic commented on tests/test_message_option.py
> +        binary2 = bytes([(97)]+[(69)]+[(188)]+[(144)]+[(113)]+[(68)])+b"abcd"+bytes([(255)])+b"temp = 22.5 C"
As above.

2019-09-30 15:28 UTC, alwa-nordic commented on tests/test_message_option.py
> +        rawdata1 = bytes([(64)]+[(0)]+[(0)]+[(0)])
As above.

2019-09-30 15:28 UTC, alwa-nordic commented on tests/test_message_option.py
> +        rawdata2 = bytes([(97)]+[(69)]+[(188)]+[(144)]+[(113)]+[(68)])+b"abcd"+bytes([(255)])+b"temp = 22.5 C"
As above.

2019-10-03 11:12 UTC, rlubos commented
Covered by #7.

2019-10-03 11:12 UTC, closed without merging